// This file was auto-generated by ML.NET Model Builder. 

using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.ML.Data;

namespace Connery.Lib
{
    public class ModelInput
    {
        [ColumnName("Label"), LoadColumn(0)]
        public string Label { get; set; }


        [ColumnName("ImageSource"), LoadColumn(1)]
        public string ImageSource { get; set; }

        public static IEnumerable<ModelInput> LoadImagesFromDirectory(string folder, bool useDirNameAsLabel = true)
        {
            string[] files;

            if (useDirNameAsLabel)
                files = Directory.GetFiles(folder, "*", SearchOption.AllDirectories);
            else
                files = Directory.GetFiles(folder);

            string[] acceptableFormats = { ".gif", ".jfif", ".jpeg", ".jpg", ".png" };
            foreach (var file in files)
            {
                if (!acceptableFormats.Contains(Path.GetExtension(file).ToLower()))
                    continue;

                yield return new ModelInput
                {
                    ImageSource = file,
                    Label = useDirNameAsLabel ? Directory.GetParent(file).Name : Path.GetFileName(file).Split('-')[0]
                };
            }
        }
    }
}
