name: Deploy on Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: Setup .NET Core 3.1.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Display .NET info
        run: dotnet --info

      - name: "Run dotnet build"
        shell: bash
        run: dotnet build webapi/Connery.WebApi.csproj --configuration Release --output ./output

      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "connery-api"
          heroku_email: "ahad@maacpiash.com"
          buildpack: jincod/dotnetcore
